AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CronBotApiAcm:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: 'api.cron-bot.com'
      ValidationMethod: DNS

Outputs:
  CronBotApiAcm:
    Value: !Ref CronBotApiAcm
    Description: Arn of cron-bot ACM resource for `api.cron-bot.com`